import { useEffect } from 'react';
import { StyleSheet, View } from 'react-native';
import Animated, {
  Easing,
  useAnimatedProps,
  useReducedMotion,
  useSharedValue,
  withDelay,
  withSpring,
  withTiming,
} from 'react-native-reanimated';
import Svg, { Circle, G, Path } from 'react-native-svg';
import { KAIROS_VIEWBOX, MOMENT_R, STREAM_PATHS } from '@/design/kairos-mark-data';
import { motion } from '@/design';

const AnimatedG = Animated.createAnimatedComponent(G);
const AnimatedCircle = Animated.createAnimatedComponent(Circle);

type Props = {
  size?: number;
  color?: string;
  /**
   * 'static'  — render the settled mark.
   * 'intro'   — play the convergence: streams sweep in staggered, then the
   *             moment-point lands. Use on splash / welcome.
   */
  mode?: 'static' | 'intro';
  onIntroEnd?: () => void;
};

/** Per-stream sweep. Extracted so hooks run a fixed number of times. */
function Stream({
  d,
  index,
  color,
  intro,
}: {
  d: string;
  index: number;
  color: string;
  intro: boolean;
}) {
  const progress = useSharedValue(intro ? 0 : 1);

  useEffect(() => {
    if (!intro) return;
    progress.value = withDelay(
      80 + index * 46,
      withTiming(1, { duration: 520, easing: Easing.bezier(0.2, 0.7, 0.2, 1) }),
    );
  }, [intro, index, progress]);

  // Streams sweep in: slightly scaled out + rotated back, resolving to rest.
  // Transform origin is the moment point (0,0 in symbol coordinates).
  const animatedProps = useAnimatedProps(() => ({
    opacity: progress.value,
    scale: 1.18 - 0.18 * progress.value,
    rotation: -10 * (1 - progress.value),
  }));

  return (
    <AnimatedG animatedProps={animatedProps} origin="0, 0">
      <Path d={d} fill={color} />
    </AnimatedG>
  );
}

/**
 * The KAIROS symbol — many streams converging into one moment.
 * Real vector geometry generated by brand/generate.mjs.
 */
export function KairosMark({ size = 64, color = '#3ED5BB', mode = 'static', onIntroEnd }: Props) {
  const reduce = useReducedMotion();
  const intro = mode === 'intro' && !reduce;
  const moment = useSharedValue(intro ? 0 : 1);

  useEffect(() => {
    if (!intro) return;
    const delay = 80 + STREAM_PATHS.length * 46 + 200;
    moment.value = withDelay(delay, withSpring(1, motion.spring.soft));
    if (onIntroEnd) {
      const t = setTimeout(onIntroEnd, delay + 500);
      return () => clearTimeout(t);
    }
  }, [intro, moment, onIntroEnd]);

  const momentProps = useAnimatedProps(() => ({
    opacity: moment.value,
    r: MOMENT_R * (0.4 + 0.6 * moment.value),
  }));

  return (
    <View style={[styles.wrap, { width: size, height: size }]}>
      <Svg width={size} height={size} viewBox={KAIROS_VIEWBOX}>
        {STREAM_PATHS.map((d, i) => (
          <Stream key={i} d={d} index={i} color={color} intro={intro} />
        ))}
        <AnimatedCircle cx={0} cy={0} fill={color} animatedProps={momentProps} />
      </Svg>
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: { alignItems: 'center', justifyContent: 'center' },
});
